fix image orientation
didi/mand-mobile pull request #724
Opened 2021-01-19 11:10 UTC by shuyanzi

当浏览器不自动修复图片角度问题时，再用代码修复图片角度

## 提交PR前

* 请认真阅读[开发指南](https://didi.github.io/mand-mobile/#/zh-CN/docs/development)
* fork **dev分支**
* 按照规范命名分支
* 需通过测试
* 提交PR至**dev分支**

## 创建PR

* 标题规则：type(scope):description，参考[规范](https://didi.github.io/mand-mobile/#/zh-CN/docs/development?anchor=Commit%E8%A7%84%E8%8C%83)
* 内容描述，参考"PR 内容区"

## 请把以上内容删除，并填写以下内容！！！

### 背景描述

### 主要改动

### 需要注意

2021-02-03 05:58 UTC, xxyan0205 commented
请提供下复现上述问题的相关设备环境信息和步骤，以及图片素材。

2021-02-25 09:18 UTC, zouhangwithsweet requested changes

2021-02-25 09:18 UTC, zouhangwithsweet commented on components/image-reader/image-processor.js
> +  if (!CSS.supports('image-orientation:none')) {
要处理 ssr 的情况
```suggestion
  if (CSS && CSS.supports && !CSS.supports('image-orientation:none')) {
```

2021-02-25 10:20 UTC, zouhangwithsweet approved these changes

2021-02-25 10:21 UTC, merged